name: neural_lns_ruc
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10.16
  - pytorch=2.0.1
  - numpy=1.24.3
  - matplotlib=3.7.1
  - networkx=2.8.8
  - pandas=1.5.3
  - scipy=1.10.1
  - pip
  - pip:
    - highs 